import "./globals.css";
import { Inter } from "next/font/google";
import { Itim } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const itim = Itim({
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={itim.className}>{children}</body>
    </html>
  );
}
